### ISSUE TITLE
Cover art extraction

### ISSUE THREAD

**Issue by alexey** [krists/id3tag#15]
Hello @krists !

I was able to find how to read image object with: `tag.get_frame :APIC`
Then I got some methods like `mime_type` and many others: `:content, :data, :id, :raw_content, :usable_content`

Those that return data/content return me some utf encoded string, at this point i was not able to save it to jpg, can you please give me clue how to forward ? 

thank you ! (will dig into lib now)

**Comment by krists** [comment]
Hello @alexey 

Thanks for giving id3tag a try. For picture frame `content` method returns the same data as `data` [method](https://github.com/krists/id3tag/blob/master/lib/id3tag/frames/v2/picture_frame.rb#L63). Both of these methods return binary data which you could then save to a file like this:
```ruby
tag = ID3Tag.read(File.open('example.mp3', 'rb'))
picture_frame = tag.get_frame(:APIC)
picture_frame .mime_type # => "image/jpeg"
File.open('pic.jpg', 'wb') { |f| f.write(picture_frame.content) }
```
Or if it is a Rails app, then you could use [send_data](http://api.rubyonrails.org/v4.2.6/classes/ActionController/DataStreaming.html#method-i-send_data) method to stream data to the browser.

**Comment by alexey** [comment]
thanks man!

I bet this will be good idea to wrap this block as a method.
Will try to find time for that

**Comment by krists** [comment]
No problem :)

You probably want to implement some if/case statement where you would check the mime type and specify right filename extension.
