### ISSUE TITLE
raised exception when a file have no id3 tag

### ISSUE THREAD

**Issue by aamir-devsinc** [krists/id3tag#16]
Hello @krists 
Here I am reading if a file have id3 tags, the file i am loading either have id3 tags or not. If file have id3tags then it is working correctly and if file has no id3 tag then it raised exception.

> NoMethodError: undefined method `unpack' for nil:NilClass
> 	from app/services/uploads/rip_id3.rb:34:in `fields'
> 	from app/services/uploads/rip_id3.rb:40:in `metadata'
> 	from app/services/uploads/rip_id3.rb:11:in `call'
> 	from app/models/concerns/service.rb:6:in `call'
> 	from (irb):7

Here is my code.
```ruby
module Uploads
  class RipId3
    include Service
    attr_reader :upload

    def initialize(upload)
      @upload = upload
    end

    def call
      upload.file_info.deep_merge!(metadata: metadata)
      upload.save!
      upload.processed!
    end

    private

    def temp_file
      @temp_file = begin
        if upload.high_res?
          open(upload.file_ref.url(:mp3))
        else
          open(upload.file_ref.url)
        end
      end
    end

    def id3_tag
        @id3_tag ||= ID3Tag.read(temp_file)
    end

    def fields
       @fields ||= id3_tag.frame_ids
    end

    def metadata
      fields.each_with_object({}) do |field, acc|
        case field
        when :TALB
          acc['album'] = id3_tag.get_frames(field).map(&:content).join(' | ')
        when :TIT2
          acc['title'] = id3_tag.get_frames(field).map(&:content).join(' | ')
        when :TPE1
          acc['artist'] = id3_tag.get_frames(field).map(&:content).join(' | ')
        when :TCON
          acc['genre'] = id3_tag.get_frames(field).map(&:content).join(' | ')
        else
          acc[field] = id3_tag.get_frames(field).map(&:content).join(' | ')
        end
      end
    end
  end
end
```

**Comment by krists** [comment]
Hello @aamir-devsinc 
Is the library used in Rails applications? It looks like there are some parts missing from the backtrace. Could you try to remove backtrace silencers by adding `Rails.backtrace_cleaner.remove_silencers!` somewhere is initializers?

ID3Tag have specs for non-audio files at https://github.com/krists/id3tag/blob/master/spec/features/can_read_non_audio_files_spec.rb but you might have a weird edge-case file that I have not thought of.

**Comment by aamir-devsinc** [comment]
Mp3 files on this page i am trying to upload for testing. These files have no id3 tags
http://www.sample-videos.com/download-sample-audio.php

**Comment by krists** [comment]
I checked the `SampleAudio_0.4mb.mp3` file. It actually have ID3v2.3 tag, but it has size `0`. But this is still a bug in `ID3Tag::Tag#frames` as it should handle such cases and return an empty array. I will release a new version soon.

**Comment by krists** [comment]
I have released new version 0.9.0 with the fix. By the way - why aren't you using getters for most common frames like `id3_tag.artist`, `id3_tag.album`.

**Comment by aamir-devsinc** [comment]
I want to get all the tags a file have. If i get common frames using getters then it will need an additional check in loop that if it frames already processed then discard it. Moreover, some files have id3tag symbols TALB, TIT2, TPE1, TCON insted album,  title, artist, genre respectively.

**Comment by aamir-devsinc** [comment]
Thanks @krists , it works.

**Comment by krists** [comment]
@aamir-devsinc Keep in mind that ID2v2.2 does have 3 character tag names instead of 4. Common attribute mapping can be seen here: https://github.com/krists/id3tag/blob/master/lib/id3tag/frame_id_advisor.rb#L5

**Comment by aamir-devsinc** [comment]
Thanks @krists , I will see it.
