### ISSUE TITLE
Support for track length?

### ISSUE THREAD

**Issue by taylorthurlow** [krists/id3tag#17]
I've looked a bit at the `ID3v1` and `ID3v2` specs, and as far as I can tell, they support a `TLEN` frame which contains the track length. None of the MP3's I have contain this frame. That said, basically every tagging utility that I've used is able to tell me the length of the tracks I give it.

Is there something obvious that I'm missing that would allow me to obtain the duration? Currently my application only grabs the file headers to get all of the tag data, so ideally I wouldn't have to download the entire file.

**Comment by krists** [comment]
Hi @taylorthurlow 

This is probably out of scope on ID3 tag library. After a quick google search i found this https://superuser.com/questions/231950/export-total-length-of-mp3-files-in-a-folder A workaround would be to process all mp3 files with this ffmpeg utility and populate `TLEN` frame for those files. This approach would let you extract not only duration of the file but also bitrate and channel info.

**Comment by taylorthurlow** [comment]
@krists Gotcha. I figured that this might be the case. I appreciate your response - and thanks for your work on the gem in general.
