### ISSUE TITLE
Does this work with chapter markers including chapter thumbnails?

### ISSUE THREAD

**Issue by johnlpollard** [krists/id3tag#20]
I couldn’t find anything in the code but wanted to make sure.

**Comment by krists** [comment]
@johnlpollard It does not do that out-of-the-box, but it would be quite easy to implement. ID3Tag gem lets you browse all frames in the tag via `get_frames` and `frames` methods. You just need to know identifier. Could that be [private frame](https://github.com/krists/id3tag/blob/master/standard_documents/id3v2.4.0-frames.txt#L1443-L1457)? You should probably go through the whole [list](https://github.com/krists/id3tag/blob/master/standard_documents/id3v2.4.0-frames.txt)
