### ISSUE TITLE
Base64 Blob

### ISSUE THREAD

**Issue by atebit** [krists/id3tag#24]
How can I use this with a base64 blob???

It wants to open files... But, I want to pass it the blob..

**Comment by krists** [comment]
Hello @atebit!

This gem works with any io-like object, as long as it responds to methods like `read`, `seak`. 

To prepare base64 encoded mp3 file for consumtion by ID3Tag you need to decode it and pass to [StringIO](https://ruby-doc.org/stdlib-2.5.1/libdoc/stringio/rdoc/StringIO.html) class.

Then you can pass this object to `ID3Tag.read` as any other file.
