### ISSUE TITLE
Integration with ActiveStorage

### ISSUE THREAD

**Issue by mvondoyannick** [krists/id3tag#30]
How can i use id3tag with activeStorage?

**Comment by mvondoyannick** [comment]
```ruby
      tag = ID3Tag.read("#{request.base_url}#{Rails.application.routes.url_helpers.rails_blob_path(@podcast.audio_file, only_path: true)}")
      puts "#{tag.artist}"
```
this integration with activeStorage send me this error
```
undefined method `seek' for #<String:0x00007f3764734dd8>
```

**Comment by krists** [comment]
Hello @mvondoyannick!

ID3Tag.read method expects opened file handle as an argument. In your example you are passing a sting with an URL.
