### ISSUE TITLE
Support for chapter frames?

### ISSUE THREAD

**Issue by domchristie** [krists/id3tag#38]
Hey there, do you have any thoughts on supporting the `CHAP` frame for chapters? I've been using this [JavaScript version](https://github.com/aadsm/jsmediatags/blob/2cc8ca5f49d788e360a3a9f18dc425e99ebf2af3/src/ID3v2FrameReader.js#L432-L457) which produces an array of chapter objects like so:

```js
{
  id: 'ch0',
  startTime: 0, // in ms
  endTime: 60000, // in ms
  startOffset: 4294967295,
  endTime: 4294967295,
  subFrames: {
    TIT2: {
      id: 'TIT2',
      size: 49,
      description: 'Title/songname/content description',
      data: 'This is a Chapter Title'
    },
    WXXX: {
      id: 'WXXX',
      size: 68,
      description: 'User defined URL link frame',
      data: {
        user_description: 'chapter url',
        data: 'https://www.example.com/foo/this-is-a-user-defined-url/'
      }
    }
  }
}
```

I'd be happy to help contribute to make this, but I might need a few pointers to get started :)

Thanks!

**Comment by krists** [comment]
Hi, @domchristie!

Looks like the original source or standard is no longer available, but it can be seen in the [web archive](https://web.archive.org/web/20131216150349/https://id3.org/Developer%20Information).

I would start by familiarise myself with the standard document and choose a good sample file. You should be able already find the frame by id and get raw content using current id3tag gem version. Once you have obtained the raw content you can create a spec example. Something similar how genre frame [is tested](https://github.com/krists/id3tag/blob/master/lib/id3tag/frames/v2/genre_frame.rb).

**Comment by domchristie** [comment]
Great, thanks!
Any thoughts on how I might tackle subframes?

**Comment by domchristie** [comment]
Posting this as a bookmark: https://mutagen-specs.readthedocs.io/en/latest/id3/id3v2-chapters-1.0.html

**Comment by krists** [comment]
Chapter frame should probably have `subframes` method that returns an array of subframes. Looks like subframes have the same signature as "normal frames" and could be initialised in same way.

Feel free to suggest interface that you would find the easiest to work with such frames - how you would like to consume the data.
